name: build and test feature branch

on:
  push:
    branches:
      - feature/*

jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull and checkout from git repository
        run: |
          echo "pulling and checking out from git repository"
